
import {AnalyseNode} from './entity'

export const grammarObject = {  // 文法产生式左侧的非终结符号与动作符等
    S: new AnalyseNode("S", AnalyseNode.NON_TERMINAL_SYMBOL),
    A: function(){return new AnalyseNode("A", AnalyseNode.NON_TERMINAL_SYMBOL)},
    B: function(){return new AnalyseNode("B", AnalyseNode.NON_TERMINAL_SYMBOL)},
    C: function(){return new AnalyseNode("C", AnalyseNode.NON_TERMINAL_SYMBOL)},
    X: function(){return new AnalyseNode("X", AnalyseNode.NON_TERMINAL_SYMBOL)},
    Y: function(){return new AnalyseNode("Y", AnalyseNode.NON_TERMINAL_SYMBOL)},
    Z: function(){return new AnalyseNode("Z", AnalyseNode.NON_TERMINAL_SYMBOL)},
    Z1: function(){return new AnalyseNode("Z'", AnalyseNode.NON_TERMINAL_SYMBOL)},
    U: function(){return new AnalyseNode("U", AnalyseNode.NON_TERMINAL_SYMBOL)},
    U1: function(){return new AnalyseNode("U'", AnalyseNode.NON_TERMINAL_SYMBOL)},
    E: function(){return new AnalyseNode("E", AnalyseNode.NON_TERMINAL_SYMBOL)},
    E1: function(){return new AnalyseNode("E'", AnalyseNode.NON_TERMINAL_SYMBOL)},
    H: function(){return new AnalyseNode("H", AnalyseNode.NON_TERMINAL_SYMBOL)},
    H1: function(){return new AnalyseNode("H'", AnalyseNode.NON_TERMINAL_SYMBOL)},
    G: function(){return new AnalyseNode("G", AnalyseNode.NON_TERMINAL_SYMBOL)},
    F: function(){return new AnalyseNode("F", AnalyseNode.NON_TERMINAL_SYMBOL)},
    D: function(){return new AnalyseNode("D", AnalyseNode.NON_TERMINAL_SYMBOL)},
    L: function(){return new AnalyseNode("L", AnalyseNode.NON_TERMINAL_SYMBOL)},
    L1: function(){return new AnalyseNode("L'", AnalyseNode.NON_TERMINAL_SYMBOL)},
    T: function(){return new AnalyseNode("T", AnalyseNode.NON_TERMINAL_SYMBOL)},
    T1: function(){return new AnalyseNode("T'", AnalyseNode.NON_TERMINAL_SYMBOL)},
    O: function(){return new AnalyseNode("O", AnalyseNode.NON_TERMINAL_SYMBOL)},
    P: function(){return new AnalyseNode("P", AnalyseNode.NON_TERMINAL_SYMBOL)},
    Q: function(){return new AnalyseNode("Q", AnalyseNode.NON_TERMINAL_SYMBOL)},
    R: function(){return new AnalyseNode("R", AnalyseNode.NON_TERMINAL_SYMBOL)},
    ADD_SUB: new AnalyseNode("@ADD_SUB", AnalyseNode.ACTION_SYMBOL),
    ADD: new AnalyseNode("@ADD", AnalyseNode.ACTION_SYMBOL),
    SUB: new AnalyseNode("@SUB", AnalyseNode.ACTION_SYMBOL),
    DIV_MUL: new AnalyseNode("@DIV_MUL", AnalyseNode.ACTION_SYMBOL),
    DIV: new AnalyseNode("@DIV", AnalyseNode.ACTION_SYMBOL),
    MUL: new AnalyseNode("@MUL", AnalyseNode.ACTION_SYMBOL),
    ASS_F: new AnalyseNode("@ASS_F", AnalyseNode.ACTION_SYMBOL),
    ASS_R: new AnalyseNode("@ASS_R", AnalyseNode.ACTION_SYMBOL),
    ASS_Q: new AnalyseNode("@ASS_Q", AnalyseNode.ACTION_SYMBOL),
    ASS_U: new AnalyseNode("@ASS_U", AnalyseNode.ACTION_SYMBOL),
    ASS_P: new AnalyseNode("@ASS_P", AnalyseNode.ACTION_SYMBOL),
    ASS_S: new AnalyseNode("@ASS_S", AnalyseNode.ACTION_SYMBOL),
    EQ: new AnalyseNode("@EQ", AnalyseNode.ACTION_SYMBOL),
    EQ_U1: new AnalyseNode("@EQ_U'", AnalyseNode.ACTION_SYMBOL),
};
